;; Exercise 1.9
;; Each of the following procedures defines a method for adding two
;; positive integers in terms of procedures inc, which increments its
;; arguments by 1.


;; procedure 1
(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))


;; procedure 2
(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5).
;; Are these procedures iterative or recursive?

;; Solution:
;; The substitution model states that whenever we encounter a procedure and want to trace it, we substitute the
;; formal parameters by the parameters passed in, and evaluate the resulting expression.
;; In this case, it means we substitute 4 for a, and 5 for b in the procedure's
;; body and evaluate the resulting expression applying the
;; substitution over and over. This means, we get a process that looks like this:

;; procedure 1: Recursive process 

;; (+ 4 5)
;; ==> (inc (+ 3 5))
;; ==> (inc (inc (+ 2 5)))
;; ==> (inc (inc (inc (+ 1 5)))) 
;; ==> (inc (inc (inc (inc (+ 0 5)))))
;; ==> (inc (inc (inc (inc 5))))
;; ==> (inc (inc (inc 6)))
;; ==> (inc (inc 7))
;; ==> (inc 8)
;; ==> 9


;; Procedure 2: Iterative process

;; (+  4 5)
;; ==> (+ 3 6)
;; ==> (+ 2 7)
;; ==> (+ 1 8)
;; ==> (+ 0 9)
;; ==> 9
